export const INCREMENT_PAGE_COUNT = "INCREMENT_PAGE_COUNT";
export const DECREMENT_PAGE_COUNT = "DECREMENT_PAGE_COUNT";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCESSFUL = "REGISTER_USER_SUCESSFUL";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
