export const INCREMENT_PAGE_COUNT = "INCREMENT_PAGE_COUNT";
export const DECREMENT_PAGE_COUNT = "DECREMENT_PAGE_COUNT";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCESSFUL = "REGISTER_USER_SUCESSFUL";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCESSFUL = "LOGIN_USER_SUCESSFUL";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const GET_LOGGEDIN_USER = "GET_LOGGEDIN_USER";
export const GET_LOGGEDIN_USER_SUCESSFUL = "GET_LOGGEDIN_USER_SUCESSFUL";
export const GET_LOGGEDIN_USER_FAILED = "GET_LOGGEDIN_USER_FAILED";
